description: 'Check if the prometheus config files are valid or not.'
parameters:
  config_file_path:
    description: The prometheus config file to validate.
    type: string
  working_directory:
    description: 'In which directory to run this command. Will be interpreted relative to the working_directory of the job). (default: .)'
    type: string
    default: '.'
steps:
  - install_promtool
  - run:
      name: 'run promtool check config'
      working_directory: <<parameters.working_directory>>
      command: promtool check config <<parameters.config_file_path>>
